export const goodReads = [
	{
		activities: [
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Shame Machine: Who Profits in the New Age of Humiliation",
				reference_activity: "(not provided)",
				created_at: "2022-08-04 16:42:37 UTC",
			},
			{
				activity_type: "Friend",
				activity: "Caelin Bryant",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin Bryant",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 16:17:11 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Ready Player One (Ready Player One, #1)",
				author: "Ernest Cline",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:18:34 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Fifth Season (The Broken Earth, #1)",
				author: "Liu Cixin",
				reference_activity: "(not provided)",
				created_at: "2022-07-29 16:12:56 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Whore Next Door: An Illustrated Memoir by Annie Campbell",
				author: "Annie Campbell",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:22:50 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Reasons for Moving, Darker & The Sargentville Not",
				author: "Mark Strand",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:24:26 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Switch Bitch",
				author: "Ronald Dahl",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:26:29 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Walk Two Moons",
				author: "Sharon Creech",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:20:50 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Reading Progress - 75%",
				posted_external_networks: "(not provided)",
				product:
					"Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead",
				author: "Brené Brown",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 01:01:25 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Communion: The Female Search for Love",
				author: "bell hooks",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:16:35 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Man on the Balcony (Martin Beck, #3)",
				author: "Maj Sjöwall",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:21:07 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"Biotic Borders: Transpacific Plant and Insect Migration and the Rise of Anti-Asian Racism in America, 1890–1950",
				author: "Jeannie N. Shinozuka",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:31:09 UTC",
			},
			{
				activity_type: "Friend",
				activity: "Caelin Bryant",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin Bryant",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-08-13 15:26:41 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Ball Lightning",
				author: "Liu Cixin",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 14:03:21 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Three-Body Problem (Remembrance of Earth’s Past, #1)",
				author: "Liu Cixin",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:14:54 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Stone Sky (The Broken Earth, #3)",
				author: "N. K. Jemisin",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 13:53:27 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
				author: "Terry Pratchett",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:21:22 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "User status for book Switch Bitch",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Reading Progress - 75%",
				posted_external_networks: "(not provided)",
				product: "Switch Bitch",
				author: "Ronald Dahl",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 01:01:16 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Lovely Bones",
				author: "Alice Sebold",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:19:51 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "User status for book Heaven",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Reading Progress - 50%",
				posted_external_networks: "(not provided)",
				product: "Heaven",
				author: "Meiko Kawakami",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 01:01:08 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity:
					"User status for book There Plant Eyes: A Personal and Cultural History of Blindness",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Reading Progress - 10%",
				posted_external_networks: "(not provided)",
				product:
					"There Plant Eyes: A Personal and Cultural History of Blindness",
				author: "M. Leona Godin",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 01:01:41 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Death's End (Remembrance of Earth’s Past, #3)",
				author: "Liu Cixin",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:15:14 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "No Longer Human",
				author: "Osamu Dazai",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:22:03 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "A Lesson Before Dying",
				author: "Ernest J. Gaines",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 13:53:53 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Do Androids Dream of Electric Sheep?",
				author: "Philip K Dick",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:20:08 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Obelisk Gate (The Broken Earth, #2)",
				author: "N. K. Jemisin",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 13:53:35 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Breasts and Eggs",
				author: "Meiko Kawakami",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 18:37:54 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"The New Jim Crow: Mass Incarceration in the Age of Colorblindness",
				author: "Michelle Alexander",
				reference_activity: "(not provided)",
				created_at: "2022-07-29 18:35:14 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Best Cat Ever",
				author: "Cleveland Amory",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:18:53 UTC",
			},
			{
				activity_type: "GoodreadsReview",
				activity:
					"Caelin Bryant's review of The New Jim Crow: Mass Incarceration in the Age of Colorblindness",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name:
					"Caelin Bryant's review of The New Jim Crow: Mass Incarceration in the Age of Colorblindness",
				posted_external_networks: "(not provided)",
				product:
					"The New Jim Crow: Mass Incarceration in the Age of Colorblindness",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 13:59:39 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Giovanni's Room",
				author: "James Baldwin",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 14:06:27 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead",
				author: "Brené Brown",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:18:18 UTC",
			},
			{
				activity_type: "BookRating",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Girl with the Dragon Tattoo (Millennium, #1)",
				author: "Stieg Larsson",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:13:17 UTC",
			},
			{
				activity_type: "Friend",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin Bryant",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-08-13 15:26:43 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"Movers and Shakers: American Women Thinkers and Activists, 1900-1970",
				author: "June Sochen",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:17:55 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Dark Forest (Remembrance of Earth’s Past, #2)",
				author: "Liu Cixin",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:15:03 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Haunting of Lin-Manuel Miranda",
				author: "Ishmael Reed",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:12:49 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Reading Progress - 75%",
				posted_external_networks: "(not provided)",
				product:
					"Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead",
				author: "Brené Brown",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 01:01:32 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Are You My Mother? A Comic Drama",
				author: "Alison Bechdel",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:25:34 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Heaven",
				author: "Meiko Kawakami",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 14:01:40 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Host (The Host, #1)",
				author: "Stephenie Meyer",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:21:45 UTC",
			},
			{
				activity_type: "BookRating",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "A Lesson Before Dying",
				reference_activity: "(not provided)",
				created_at: "2022-09-19 13:53:56 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Girl Who Played with Fire (Millennium, #2)",
				author: "Stieg Larsson",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:19:21 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"I Am Malala: The Story of the Girl Who Stood Up for Education and Was Shot by the Taliban",
				author: "Malala Yousafzai",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:20:34 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy",
				author: "Cathy O'Neil",
				reference_activity: "(not provided)",
				created_at: "2022-08-04 16:42:50 UTC",
			},
			{
				activity_type: "Friend",
				activity: "Caelin Bryant",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin Bryant",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-08-23 01:37:13 UTC",
			},
			{
				activity_type: "GoodreadsReview",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin Bryant's review of Heaven",
				posted_external_networks: "(not provided)",
				product: "Heaven",
				reference_activity: "(not provided)",
				created_at: "2022-09-21 16:17:28 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Girl Who Kicked the Hornet's Nest (Millennium, #3)",
				author: "Stieg Larsson",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:19:28 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"There Plant Eyes: A Personal and Cultural History of Blindness",
				author: "M. Leona Godin",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:15:44 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Bitter Fruit",
				author: "Achmat Dangor",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:25:12 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Stranger Beside Me: Ted Bundy: The Shocking Inside Story",
				author: "Ann Rule",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:21:37 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "Blindness",
				author: "José Saramago",
				reference_activity: "(not provided)",
				created_at: "2022-08-22 23:58:00 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product:
					"The Man from the Train: The Solving of a Century-Old Serial Killer Mystery",
				author: "Bill James",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:17:20 UTC",
			},
			{
				activity_type: "UserChallenge",
				activity: "Caelin’s challenge",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin’s challenge",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:10:23 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "The Alchemist",
				author: "Paulo Coelho",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:20:21 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "How to Speak Machine: Laws of Design for a Digital Age",
				author: "John Maeda",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:16:56 UTC",
			},
			{
				activity_type: "Follow",
				activity: "Caelin is now following Amari’s reviews",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "Caelin is now following Amari’s reviews",
				posted_external_networks: "(not provided)",
				product: "(not provided)",
				reference_activity: "(not provided)",
				created_at: "2022-08-13 15:24:32 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				is_visible: "Yes",
				activity_name: "(not provided)",
				posted_external_networks: "(not provided)",
				product: "A Wrinkle in Time (Time Quintet, #1)",
				author: "Madeleine L'Engle",
				reference_activity: "(not provided)",
				created_at: "2022-07-28 21:23:56 UTC",
			},
		],
		feeds: [
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 18:37:54 UTC",
				updated_at: "2022-09-21 18:37:54 UTC",
			},
			{
				activity_type: "GoodreadsReview",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 16:17:28 UTC",
				updated_at: "2022-09-21 16:17:28 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity:
					"User status for book There Plant Eyes: A Personal and Cultural History of Blindness",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 01:01:41 UTC",
				updated_at: "2022-09-21 01:01:41 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 01:01:32 UTC",
				updated_at: "2022-09-21 01:01:32 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 01:01:25 UTC",
				updated_at: "2022-09-21 01:01:25 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "User status for book Switch Bitch",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 01:01:16 UTC",
				updated_at: "2022-09-21 01:01:16 UTC",
			},
			{
				activity_type: "ReadingProgress",
				activity: "User status for book Heaven",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-21 01:01:08 UTC",
				updated_at: "2022-09-21 01:01:08 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 14:06:27 UTC",
				updated_at: "2022-09-19 14:06:27 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 14:03:21 UTC",
				updated_at: "2022-09-19 14:03:21 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 14:01:40 UTC",
				updated_at: "2022-09-19 14:01:40 UTC",
			},
			{
				activity_type: "GoodreadsReview",
				activity:
					"Caelin Bryant's review of The New Jim Crow: Mass Incarceration in the Age of Colorblindness",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 13:59:39 UTC",
				updated_at: "2022-09-19 13:59:39 UTC",
			},
			{
				activity_type: "BookRating",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 13:53:56 UTC",
				updated_at: "2022-09-19 13:53:56 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 13:53:53 UTC",
				updated_at: "2022-09-19 13:53:53 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 13:53:35 UTC",
				updated_at: "2022-09-19 13:53:35 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-09-19 13:53:27 UTC",
				updated_at: "2022-09-19 13:53:27 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-08-22 23:58:00 UTC",
				updated_at: "2022-08-22 23:58:00 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-08-04 16:42:50 UTC",
				updated_at: "2022-08-04 16:42:50 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-08-04 16:42:37 UTC",
				updated_at: "2022-08-04 16:42:37 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-29 18:35:14 UTC",
				updated_at: "2022-07-29 18:35:14 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-29 16:12:56 UTC",
				updated_at: "2022-07-29 16:12:56 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:31:09 UTC",
				updated_at: "2022-07-28 21:31:09 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:26:29 UTC",
				updated_at: "2022-07-28 21:26:29 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:25:34 UTC",
				updated_at: "2022-07-28 21:25:34 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:25:12 UTC",
				updated_at: "2022-07-28 21:25:12 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:24:26 UTC",
				updated_at: "2022-07-28 21:24:26 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:23:56 UTC",
				updated_at: "2022-07-28 21:23:56 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:22:50 UTC",
				updated_at: "2022-07-28 21:22:50 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:22:03 UTC",
				updated_at: "2022-07-28 21:22:03 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:21:45 UTC",
				updated_at: "2022-07-28 21:21:45 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:21:37 UTC",
				updated_at: "2022-07-28 21:21:37 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:21:22 UTC",
				updated_at: "2022-07-28 21:21:22 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:21:07 UTC",
				updated_at: "2022-07-28 21:21:07 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:20:50 UTC",
				updated_at: "2022-07-28 21:20:50 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:20:34 UTC",
				updated_at: "2022-07-28 21:20:34 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:20:21 UTC",
				updated_at: "2022-07-28 21:20:21 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:20:08 UTC",
				updated_at: "2022-07-28 21:20:08 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:19:51 UTC",
				updated_at: "2022-07-28 21:19:51 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:19:28 UTC",
				updated_at: "2022-07-28 21:19:28 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:19:21 UTC",
				updated_at: "2022-07-28 21:19:21 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:18:53 UTC",
				updated_at: "2022-07-28 21:18:53 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:18:34 UTC",
				updated_at: "2022-07-28 21:18:34 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:18:18 UTC",
				updated_at: "2022-07-28 21:18:18 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:17:55 UTC",
				updated_at: "2022-07-28 21:17:55 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:17:20 UTC",
				updated_at: "2022-07-28 21:17:20 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:16:56 UTC",
				updated_at: "2022-07-28 21:16:56 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:16:35 UTC",
				updated_at: "2022-07-28 21:16:35 UTC",
			},
			{
				activity_type: "BookStatusReading",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:15:44 UTC",
				updated_at: "2022-07-28 21:15:44 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:15:14 UTC",
				updated_at: "2022-07-28 21:15:14 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:15:03 UTC",
				updated_at: "2022-07-28 21:15:03 UTC",
			},
			{
				activity_type: "BookStatusRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:14:54 UTC",
				updated_at: "2022-07-28 21:14:54 UTC",
			},
			{
				activity_type: "BookRating",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:13:17 UTC",
				updated_at: "2022-07-28 21:13:17 UTC",
			},
			{
				activity_type: "BookStatusWantToRead",
				activity: "(not provided)",
				user: "Caelin Bryant",
				parent_activity_type: "(not provided)",
				created_at: "2022-07-28 21:12:49 UTC",
				updated_at: "2022-07-28 21:12:49 UTC",
			},
		],
	},
];
